urls.py
from django.urls import path

from . import views

app_name= 'register'

urlpatterns = [
    path('', views.index, name='index'),
      
    path('<int:student_id>/', views.detail, name='detail'),
   
    path('<int:student_id>/results/', views.results, name='results'),
    
    path('<int:student_id>/vote/', views.vote, name='vote'),
]

models.py
from django.db import models
import datetime
from django.utils import timezone

class Student_registration(models.Model):
    student_name = models.CharField(max_length=224)
    student_date_of_birth = models.CharField(max_length=224)
    student_date_of_registration=models.DateTimeField('date_of_registration')
    student_sex=models.CharField(max_length=224)
    student_aadhaar_num=models.BigIntegerField()
    student_email_id=models.EmailField(max_length=224)
    

    def __str__(self):
        return f'{self.student_name},{self.student_date_of_birth},{self.student_date_of_registration},{self.student_sex},{self.student_aadhaar_num},{self.student_email_id}'

    def recently_registered(self):
        return self.student_date_of_registration >= timezone.now() - datetime.timedelta(days=27)  

class School(models.Model):
    student=models.ForeignKey(Student_registration, on_delete=models.CASCADE)
    school_name=models.CharField(max_length=224)
    courses=models.CharField(max_length=224)
    output=models.CharField(max_length=224)
    choices = models.IntegerField(default=0)

views.py
from django.template import loader
from .models import Student_registration,School
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


def index(request):
    latest_student = Student_registration.objects.order_by('-student_date_of_registration')[:2]
    # output = '&'.join([x.student_name for x in latest_student])
    # return HttpResponse(output)

    # template = loader.get_template('register/index.html')
    # context = {'latest_student': latest_student,}
    # return HttpResponse(template.render(context, request))

    context = {'latest_student': latest_student}
    return render(request, 'register/index.html', context)

def detail(request, student_id):
    # return HttpResponse("You're looking at student %s." % student_id)
    x = Student_registration.objects.get(pk=student_id)
    return render(request, 'register/detail.html', {'x': x})

# def results(request, student_id):
#     response = "You're looking at the results of student %s."
#     return HttpResponse(response % student_id)

def results(request, student_id):
    x = Student_registration.objects.get(pk=student_id)
    return render(request, 'register/results.html', {'x': x})

# def vote(request, student_id):
#     return HttpResponse("You're voting on student %s." % student_id)
def vote(request, student_id):
    x= get_object_or_404(Student_registration, pk=student_id)
    try:
        selected = x.school_set.get(pk=request.POST['z'])
    except (KeyError, School.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'register/detail.html', {
            'x': x,
            'error_message': "You didnot select a choice!!",
        })
    else:
        selected.choices += 1
        selected.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('register:results', args=(x.id,)))

templates/register/detail.html
<!-- {{ x }} -->


<!-- <h1>{{ x.student_name }}</h1>

<ul>
{% for y in x.school_set.all %}
    <li>{{ y.school_name }}</li>
{% endfor %}
</ul> -->

<form action="{% url 'register:vote' x.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <h1>{{ x.student_name }}</h1>

        {% for z in x.school_set.all %}
            <input type="radio" name="z" id="z{{ forloop.counter }}" value="{{ z.id }}">
            <label for="z{{ forloop.counter }}">{{ z.school_name }}</label>
        {% endfor %}
    </fieldset>
    <input type="submit" value="vote">
</form>

templates/register/index.html
{% if latest_student %}
    <ul>
    {% for x in latest_student %}
        <li>
            <!-- <a href="/register/{{ x.id }}/"> -->
            <a href="{% url 'register:detail' x.id %}"></a>
                {{ x.student_name }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% endif %}

templates/register/results.html
<h1>{{ x.student_name }}</h1>

<ul>
{% for y in x.school_set.all %}
    <li>{{ y.school_name }} -- {{ y.choices }} vote{{ y.choices|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'register:detail' x.id %}">Vote again?</a>